version: "3.7"

services:
  mongodb:
    image: mongo:4.4
    container_name: "mongodb"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rpdly-service

    ports:
      - 27017:27017
    volumes:
      - /usr/local/rpdly/mongodb:/data/db